import XCTest
@testable import AdventOfCode2019

final class IntcodeTestsDay5: XCTestCase {

  func testInputOutput() throws {
    let outputWasProvided = expectation(description: "An output should be generated by the intcode program")
    let machine = IntcodeMachine(program: [3,0,4,0,99], inputProvider: JustInputProvider([1337]), outputProvider: ClosureOutputProvider { output in
      XCTAssertEqual(output, 1337)
      outputWasProvided.fulfill()
    })

    XCTAssertNoThrow(try machine.execute())

    waitForExpectations(timeout: 1, handler: nil)
  }

}
