import Testing

@testable import AdventOfCode2025

// Make a copy of this file for every day to ensure the provided smoke tests
// pass.
struct Day07Tests {
    // Smoke test data provided in the challenge question
    let testData = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

    @Test func testPart1() async throws {
        let challenge = Day07(data: testData)
        #expect(String(describing: challenge.part1()) == "21")
    }
}
