name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Show Swift version 
      run: swift --version
    - name: Run tests
      run: swift test
